Add LibreSSL and Picotls+LibreSSL to CI
ngtcp2/ngtcp2 pull request #1284
Opened 2024-08-03 08:41 UTC by nak3

As current CI does not run with LibreSSL, some changes introduces
build failure for LibreSSL and need some fixes like bd5368b.

Hence, this patch adds LibreSSL and Picotls+LibreSSL to CI.

2024-08-03 08:49 UTC, nak3 commented
As per https://github.com/ngtcp2/ngtcp2/issues/935#issuecomment-1708563444, it might be better to have its own separated library to avoid a lot of ifdef. (I agree with that.)
However, this PR didn't create the separated library to make change small as much as possible.

Also, please be aware that this PR bumped Picotls version to include the following commits:

* https://github.com/h2o/picotls/commit/a8d42c08b6c3744a248e043abd837ba216f2444a
* https://github.com/h2o/picotls/commit/cae16c843588c836656f5c07f1a4f25323c885dc

2024-08-05 08:24 UTC, tatsuhiro-t requested changes

2024-08-05 08:24 UTC, tatsuhiro-t commented on .github/workflows/build.yml
> -
Please do not remove empty lines unless it is absolutely needed for this change.

2024-08-05 08:24 UTC, tatsuhiro-t commented on ci/build_libressl.sh
> +mkdir build
There is no need to create build directory explicitly here.

2024-08-05 08:24 UTC, tatsuhiro-t commented on ci/build_libressl.sh
> +# build patched libressl (for GitHub workflow)
I think we use official libressl and not patched one.

2024-08-05 09:30 UTC, nak3 commented
Thank you so much! Updated.

2024-08-05 09:39 UTC, tatsuhiro-t commented
LGTM.  Thank you.  Could you squash commits into one?

2024-08-05 09:39 UTC, tatsuhiro-t approved these changes

2024-08-05 09:47 UTC, merged

2024-08-05 09:47 UTC, tatsuhiro-t commented
Thank you for PR.  Merged now.