ngtcp2_conn_write_datagram conveniently accepts single buffer
ngtcp2/ngtcp2 pull request #991
Opened 2023-10-27 20:52 UTC by mikeswhite1

Similar convenience API already exists for write_stream

2023-10-28 03:43 UTC, tatsuhiro-t requested changes

2023-10-28 03:43 UTC, tatsuhiro-t commented on lib/includes/ngtcp2/ngtcp2.h
> +                                    FLAGS, DGRAM_ID, DATAV, DATAVCNT, TS)      \
```suggestion
                                    FLAGS, DGRAM_ID, DATA, DATALEN, TS)      \
```

2023-10-30 01:05 UTC, mikeswhite1 commented on lib/includes/ngtcp2/ngtcp2.h
> +                                    FLAGS, DGRAM_ID, DATAV, DATAVCNT, TS)      \
Thank you for the catch 🙏

2023-10-30 08:19 UTC, merged

2023-10-30 08:19 UTC, tatsuhiro-t commented
Thank you for PR.  Merged now.